name: geoenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.7.0=py311haa95532_0
  - aom=3.6.0=hd77b12b_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h827c3e9_1
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.4=py311haa95532_0
  - attrs=24.3.0=py311haa95532_0
  - babel=2.16.0=py311haa95532_0
  - beautifulsoup4=4.13.4=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py311haa95532_0
  - blosc=1.21.6=h4190f5b_0
  - bottleneck=1.4.2=py311h57dcf0c_0
  - branca=0.6.0=py311haa95532_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.8.3=h4c7d964_0
  - cairo=1.16.0=h85cdd14_6
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py311h214f63a_0
  - cpuonly=2.0=0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.15=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.55.3=py311h827c3e9_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=hd7a5696_0
  - fribidi=1.0.10=h62dcd97_0
  - geopandas=1.0.1=py311haa95532_0
  - geopandas-base=1.0.1=py311haa95532_0
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=hbf7d8e7_4
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_0
  - harfbuzz=10.2.0=he2f9f60_1
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - imbalanced-learn=0.13.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.0=pyh3521513_0
  - ipython=9.4.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=8.1.5=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.1=py311haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.4.4=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.27.3=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.21.3=hcb72d8e_3
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libarchive=3.7.7=h9243413_0
  - libavif=1.1.1=h827c3e9_0
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - libcurl=8.14.1=h2300eb9_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal-core=3.11.0=ha9257c9_0
  - libglib=2.84.2=h405b238_0
  - libgomp=15.1.0=h1383e82_4
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=h135ad9c_1
  - libjpeg-turbo=2.1.4=hcfcfb64_0
  - libkml=1.3.0=h63940dd_7
  - libkrb5=1.21.3=hcb72d8e_3
  - liblapack=3.9.0=12_win64_mkl
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.18=h62dcd97_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.3.2=h3d04722_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxgboost=3.0.3=cpu_hd161407_0
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.2.13=h2466b09_6
  - lz4-c=1.9.4=h2bbff1b_1
  - mapclassify=2.9.0=py311haa95532_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.0=py311haa95532_0
  - matplotlib-base=3.10.0=py311he19b0ae_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.3=hb68bac4_0
  - mistune=3.1.2=py311haa95532_0
  - mkl-service=2.4.0=py311h2bbff1b_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.4.2=py311haa95532_0
  - notebook=7.4.4=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numexpr=2.8.4=py311hffd1eac_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.1=h725018a_0
  - overrides=7.4.0=py311haa95532_0
  - packaging=25.0=py311haa95532_0
  - pandas=2.3.1=py311h885b0b7_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py311haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py311hb328d1f_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=4.3.8=pyhe01879c_0
  - proj=9.3.1=h4c8f42b_1
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py311he736701_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.3=cpu_pyh718b53a_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.10.0=py311h10c4007_1
  - pyparsing=3.2.0=py311haa95532_0
  - pyproj=3.6.1=py311h8a0a45e_1
  - pyqt=6.7.1=py311h378bd72_2
  - pyqt6-sip=13.9.1=py311h02ab6af_2
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.9=h631f459_0_cpython
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-json-logger=3.2.1=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=8_cp311
  - pytorch=2.3.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=26.2.0=py311h5da7b33_0
  - qtbase=6.7.3=hd088775_4
  - qtconsole=5.6.1=py311haa95532_1
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtpy=2.4.1=py311haa95532_0
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - referencing=0.30.2=py311haa95532_0
  - requests=2.32.4=py311haa95532_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - scikit-learn=1.6.1=py311h585ebfc_0
  - seaborn=0.13.2=py311haa95532_3
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=78.1.1=py311haa95532_0
  - shapely=2.1.1=py311hbe77627_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sklearn-compat=0.1.3=pyhd8ed1ab_0
  - sniffio=1.3.0=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - terminado=0.17.1=py311haa95532_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.14=h5e9d12e_1
  - torchaudio=2.3.1=py311_cpu
  - torchvision=0.18.1=py311_cpu
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - uriparser=0.9.8=h1a0bd13_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.13=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xerces-c=3.2.4=hd77b12b_1
  - xgboost=3.0.3=cpu_pyhb39878e_0
  - xyzservices=2022.9.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - click==8.2.1
      - einops==0.7.0
      - fastapi==0.116.1
      - flatbuffers==25.2.10
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - huggingface-hub==0.34.4
      - intel-openmp==2021.4.0
      - keras==3.11.1
      - libclang==18.1.1
      - lightning-utilities==0.15.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mkl==2021.4.0
      - ml-dtypes==0.5.3
      - multidict==6.6.3
      - namex==0.1.0
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - propcache==0.3.2
      - protobuf==5.28.3
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-multipart==0.0.20
      - pytorch-lightning==2.4.0
      - pytorch-tabnet==4.1.0
      - pytorch-tabular==1.1.1
      - regex==2025.7.34
      - rich==14.1.0
      - safetensors==0.6.2
      - scipy==1.16.1
      - starlette==0.47.2
      - tbb==2021.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchmetrics==1.5.2
      - tqdm==4.67.1
      - transformers==4.55.0
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.20.1
prefix: C:\Users\USER\anaconda3\envs\geoenv
